/* 회원 */
CREATE TABLE A_USER (
	U_NO INTEGER NOT NULL, /* 회원번호 */
	ID VARCHAR2(20), /* 아이디 */
	PWD VARCHAR2(20), /* 비밀번호 */
	NAME VARCHAR2(20), /* 이름 */
	NICK VARCHAR2(10), /* 닉네임 */
	POS VARCHAR2(20), /* 직급 */
	LOC VARCHAR2(40), /* 매장 */
	HIREDATE DATE, /* 입사일 */
	MONTH INTEGER, /* 근속개월수 */
	SAL INTEGER, /* 연봉 */
	PAY INTEGER, /* 시급 */
	BIRTH VARCHAR2(20), /* 생년월일 */
	TEL VARCHAR2(13), /* 전화번호 */
	ADDR VARCHAR2(50), /* 주소 */
	EMAIL VARCHAR2(30), /* 이메일 */
	GENDER INTEGER, /* 성별 */
	POINT INTEGER, /* 포인트 */
	gb_out VARCHAR2(1), /* 탈퇴여부 */
	picture INTEGER /* 프로필 사진 */
);

CREATE UNIQUE INDEX PK_A_USER
	ON A_USER (
		U_NO ASC
	);

ALTER TABLE A_USER
	ADD
		CONSTRAINT PK_A_USER
		PRIMARY KEY (
			U_NO
		);

/* 제품 */
CREATE TABLE A_PRODUCT (
	NUM VARCHAR2(5) NOT NULL, /* 제품번호 */
	U_NO INTEGER NOT NULL, /* 회원번호 */
	NAME VARCHAR2(20) NOT NULL, /* 제품명 */
	CLASS VARCHAR2(20), /* 분류 */
	COST INTEGER, /* 금액 */
	CNT INTEGER, /* 판매수량 */
	POS VARCHAR2(20) /* 조회제한 */
);

CREATE UNIQUE INDEX PK_A_PRODUCT
	ON A_PRODUCT (
		NUM ASC
	);

ALTER TABLE A_PRODUCT
	ADD
		CONSTRAINT PK_A_PRODUCT
		PRIMARY KEY (
			NUM
		);

/* 일매출 */
CREATE TABLE A_DAILYSALES (
	A_DATE DATE NOT NULL, /* 조회일자 */
	DAILYSALES INTEGER, /* 매출 */
	CNT INTEGER /* 방문인원 */
);

CREATE UNIQUE INDEX PK_A_DAILYSALES
	ON A_DAILYSALES (
		A_DATE ASC
	);

ALTER TABLE A_DAILYSALES
	ADD
		CONSTRAINT PK_A_DAILYSALES
		PRIMARY KEY (
			A_DATE
		);

/* 게시판 */
CREATE TABLE A_BOARD (
	NUM INTEGER NOT NULL, /* 게시물번호 */
	U_NO INTEGER, /* 회원번호 */
	TITLE VARCHAR2(20), /* 제목 */
	Writer VARCHAR2(20), /* 작성자 */
	W_DATE DATE, /* 작성시간 */
	content VARCHAR2(500), /* 내용 */
	GOOD INTEGER, /* 추천 */
	Notice VARCHAR2(1), /* 공지사항 */
	gb_del VARCHAR2(1) /* 삭제여부 */
);

CREATE UNIQUE INDEX PK_A_BOARD
	ON A_BOARD (
		NUM ASC
	);

ALTER TABLE A_BOARD
	ADD
		CONSTRAINT PK_A_BOARD
		PRIMARY KEY (
			NUM
		);

/* 댓글 */
CREATE TABLE A_COMMENTS (
	CNT INTEGER NOT NULL, /* 댓글수 */
	NUM INTEGER, /* 게시물번호 */
	U_NO INTEGER, /* 회원번호 */
	CONTENT VARCHAR2(100), /* 댓글내용 */
	Writer VARCHAR2(20), /* 댓글작성자 */
	W_DATE DATE, /* 댓글작성시간 */
	gb_del VARCHAR2(1) /* 삭제여부 */
);

CREATE UNIQUE INDEX PK_A_COMMENTS
	ON A_COMMENTS (
		CNT ASC
	);

ALTER TABLE A_COMMENTS
	ADD
		CONSTRAINT PK_A_COMMENTS
		PRIMARY KEY (
			CNT
		);

/* 근태여부 */
CREATE TABLE A_ABS (
	U_NO INTEGER NOT NULL, /* 회원번호 */
	NAME VARCHAR2(20) NOT NULL, /* 이름 */
	A_DATE DATE, /* 근무일 */
	ABS VARCHAR2(1), /* 출근여부 */
	INTIME DATE, /* 출근시간 */
	OUTTIME DATE, /* 퇴근시간 */
	ALLTIME DATE /* 총근무시간 */
);

CREATE UNIQUE INDEX PK_A_ABS
	ON A_ABS (
		U_NO ASC
	);

ALTER TABLE A_ABS
	ADD
		CONSTRAINT PK_A_ABS
		PRIMARY KEY (
			U_NO
		);

/* 장바구니 */
CREATE TABLE A_SHOPPING (
	NUM VARCHAR2(5) NOT NULL, /* 제품번호 */
	U_NO INTEGER NOT NULL, /* 회원번호 */
	CNT INTEGER, /* 총 수량 */
	POINT INTEGER, /* 지급 포인트 */
	COST INTEGER /* 총 금액 */
);

CREATE UNIQUE INDEX PK_A_SHOPPING
	ON A_SHOPPING (
		NUM ASC
	);

ALTER TABLE A_SHOPPING
	ADD
		CONSTRAINT PK_A_SHOPPING
		PRIMARY KEY (
			NUM
		);

/* 급여 */
CREATE TABLE A_COMM (
	U_NO INTEGER NOT NULL, /* 회원번호 */
	NAME VARCHAR2(20) NOT NULL, /* 이름 */
	POS VARCHAR2(20), /* 직급 */
	TIME DATE, /* 근무시간 */
	C_DATE DATE, /* 급여일 */
	W_INCEN INTEGER, /* 주휴수당 */
	N_INCEN INTEGER, /* 야간근무수당 */
	INCEN INTEGER, /* 인센티브 */
	TOTAL INTEGER, /* 총급여 */
	MINUS INTEGER, /* 공제금액 */
	REAL INTEGER /* 실지급액 */
);

CREATE UNIQUE INDEX PK_A_COMM
	ON A_COMM (
		U_NO ASC
	);

ALTER TABLE A_COMM
	ADD
		CONSTRAINT PK_A_COMM
		PRIMARY KEY (
			U_NO
		);

/* 직원스케줄 */
CREATE TABLE A_Schedule (
	U_NO INTEGER NOT NULL, /* 회원번호 */
	NAME VARCHAR2(20) NOT NULL, /* 이름 */
	POS VARCHAR2(20), /* 직급 */
	W_DATE DATE, /* 근무일 */
	INTIME DATE, /* 출근시간 */
	OUTTIME DATE, /* 퇴근시간 */
	TOTAL DATE /* 총근무시간 */
);

CREATE UNIQUE INDEX PK_A_Schedule
	ON A_Schedule (
		U_NO ASC
	);

ALTER TABLE A_Schedule
	ADD
		CONSTRAINT PK_A_Schedule
		PRIMARY KEY (
			U_NO
		);

/* 주간매출 */
CREATE TABLE A_WEEKSALES (
	A_DATE DATE NOT NULL, /* 조회일자 */
	WEEKSALES INTEGER, /* 주간매출 */
	AVERAGE INTEGER /* 평균매출 */
);

CREATE UNIQUE INDEX PK_A_WEEKSALES
	ON A_WEEKSALES (
		A_DATE ASC
	);

ALTER TABLE A_WEEKSALES
	ADD
		CONSTRAINT PK_A_WEEKSALES
		PRIMARY KEY (
			A_DATE
		);

/* 월매출 */
CREATE TABLE A_MONTHSALES (
	A_DATE DATE NOT NULL, /* 조회일자 */
	MONTHSALES INTEGER, /* 월간매출 */
	AVERAGE INTEGER /* 평균매출 */
);

CREATE UNIQUE INDEX PK_A_MONTHSALES
	ON A_MONTHSALES (
		A_DATE ASC
	);

ALTER TABLE A_MONTHSALES
	ADD
		CONSTRAINT PK_A_MONTHSALES
		PRIMARY KEY (
			A_DATE
		);

/* 시간대별매출 */
CREATE TABLE A_TIMESALES (
	A_DATE DATE NOT NULL, /* 조회일자 */
	TIME DATE, /* 판매시간 */
	SALES INTEGER, /* 매출 */
	CNT INTEGER /* 방문인원 */
);

CREATE UNIQUE INDEX PK_A_TIMESALES
	ON A_TIMESALES (
		A_DATE ASC
	);

ALTER TABLE A_TIMESALES
	ADD
		CONSTRAINT PK_A_TIMESALES
		PRIMARY KEY (
			A_DATE
		);

/* 매장정보 */
CREATE TABLE A_STORE (
	LOC VARCHAR2(40) NOT NULL, /* 매장 */
	ADDR VARCHAR2(30), /* 주소 */
	OPERATE VARCHAR2(14), /* 운영시간 */
	RM VARCHAR2(20) /* 점장 */
);

CREATE UNIQUE INDEX PK_A_STORE
	ON A_STORE (
		LOC ASC
	);

ALTER TABLE A_STORE
	ADD
		CONSTRAINT PK_A_STORE
		PRIMARY KEY (
			LOC
		);

/* 추천 */
CREATE TABLE A_GOOD (
	U_NO INTEGER NOT NULL, /* 회원번호 */
	NUM INTEGER NOT NULL, /* 게시물번호 */
	gb_yn INTEGER /* 추천여부 */
);

CREATE UNIQUE INDEX PK_A_GOOD
	ON A_GOOD (
		U_NO ASC,
		NUM ASC
	);

ALTER TABLE A_GOOD
	ADD
		CONSTRAINT PK_A_GOOD
		PRIMARY KEY (
			U_NO,
			NUM
		);

ALTER TABLE A_USER
	ADD
		CONSTRAINT FK_A_STORE_TO_A_USER
		FOREIGN KEY (
			LOC
		)
		REFERENCES A_STORE (
			LOC
		);

ALTER TABLE A_PRODUCT
	ADD
		CONSTRAINT FK_A_SHOPPING_TO_A_PRODUCT
		FOREIGN KEY (
			NUM
		)
		REFERENCES A_SHOPPING (
			NUM
		);

ALTER TABLE A_PRODUCT
	ADD
		CONSTRAINT FK_A_USER_TO_A_PRODUCT
		FOREIGN KEY (
			U_NO
		)
		REFERENCES A_USER (
			U_NO
		);

ALTER TABLE A_BOARD
	ADD
		CONSTRAINT FK_A_USER_TO_A_BOARD
		FOREIGN KEY (
			U_NO
		)
		REFERENCES A_USER (
			U_NO
		);

ALTER TABLE A_COMMENTS
	ADD
		CONSTRAINT FK_A_BOARD_TO_A_COMMENTS
		FOREIGN KEY (
			NUM
		)
		REFERENCES A_BOARD (
			NUM
		);

ALTER TABLE A_COMMENTS
	ADD
		CONSTRAINT FK_A_USER_TO_A_COMMENTS
		FOREIGN KEY (
			U_NO
		)
		REFERENCES A_USER (
			U_NO
		);

ALTER TABLE A_ABS
	ADD
		CONSTRAINT FK_A_USER_TO_A_ABS
		FOREIGN KEY (
			U_NO
		)
		REFERENCES A_USER (
			U_NO
		);

ALTER TABLE A_SHOPPING
	ADD
		CONSTRAINT FK_A_USER_TO_A_SHOPPING
		FOREIGN KEY (
			U_NO
		)
		REFERENCES A_USER (
			U_NO
		);

ALTER TABLE A_COMM
	ADD
		CONSTRAINT FK_A_USER_TO_A_COMM
		FOREIGN KEY (
			U_NO
		)
		REFERENCES A_USER (
			U_NO
		);

ALTER TABLE A_Schedule
	ADD
		CONSTRAINT FK_A_USER_TO_A_Schedule
		FOREIGN KEY (
			U_NO
		)
		REFERENCES A_USER (
			U_NO
		);

ALTER TABLE A_GOOD
	ADD
		CONSTRAINT FK_A_USER_TO_A_GOOD
		FOREIGN KEY (
			U_NO
		)
		REFERENCES A_USER (
			U_NO
		);

ALTER TABLE A_GOOD
	ADD
		CONSTRAINT FK_A_BOARD_TO_A_GOOD
		FOREIGN KEY (
			NUM
		)
		REFERENCES A_BOARD (
			NUM
		);