-- 엔티티 관계도
SELECT *
FROM COUNTRIES;

SELECT *
FROM REGIONS;

SELECT *
FROM LOCATIONS;
SELECT *
FROM DEPARTMENTS;
SELECT *
FROM EMPLOYEES;

-- 실습 12
SELECT r.REGION_ID ,r.REGION_NAME ,c.COUNTRY_NAME 
FROM COUNTRIES c, REGIONS r 
WHERE r.REGION_ID = c.REGION_ID 
AND r.REGION_ID IN(1);

-- 실습 13
SELECT r.REGION_ID ,r.REGION_NAME ,c.COUNTRY_NAME ,l.CITY 
FROM COUNTRIES c, REGIONS r ,LOCATIONS l
WHERE r.REGION_ID = c.REGION_ID 
AND c.COUNTRY_ID = l.COUNTRY_ID  
AND r.REGION_ID = 1;

-- 실습 14
SELECT c.REGION_ID ,r.REGION_NAME ,c.COUNTRY_NAME ,l.CITY ,d.DEPARTMENT_NAME 
FROM COUNTRIES c, REGIONS r ,LOCATIONS l,DEPARTMENTS d 
WHERE c.REGION_ID = r.REGION_ID
AND c.COUNTRY_ID = l.COUNTRY_ID
AND l.LOCATION_ID = d.location_id
AND c.region_ID = 1;
 

-- 실습 15
SELECT c.REGION_ID ,r.REGION_NAME ,c.COUNTRY_NAME ,l.CITY ,d.DEPARTMENT_NAME, CONCAT(E.FIRST_NAME,E.LAST_NAME) NAME  
FROM COUNTRIES c, REGIONS r ,LOCATIONS l,DEPARTMENTS d, EMPLOYEES e 
WHERE c.REGION_ID = r.REGION_ID
AND c.COUNTRY_ID = l.COUNTRY_ID
AND l.LOCATION_ID = d.location_id
AND d.DEPARTMENT_ID  =  e.DEPARTMENT_ID 
AND c.region_ID = 1;

-- 실습 16

SELECT e.EMPLOYEE_ID ,CONCAT(FIRST_NAME,LAST_NAME) NAME,J.JOB_ID,JOB_TITLE 
FROM JOBS j ,EMPLOYEES e  
WHERE j.JOB_ID = e.JOB_ID;

-- 실습 17
SELECT e.MANAGER_ID MGR_ID, 
	   CONCAT(E2.FIRST_NAME,E2.LAST_NAME) MGR_NAME, 
	   e.EMPLOYEE_ID ,
	   CONCAT(E.FIRST_NAME,E.LAST_NAME),
	   e.job_id,
	   j.job_title	   
FROM JOBS j ,EMPLOYEES e ,EMPLOYEES e2 
WHERE e.JOB_ID  = j.JOB_ID
AND E.MANAGER_ID = E2.EMPLOYEE_ID;






